### ISSUE TITLE
elm-package is broken on my system – fileAccess: permission denied

### ISSUE THREAD

**Issue by srid** [elm-lang/elm-package#109] opened 2015-06-15 17:11 UTC
I'm running OS X El Capitan, and elm-package is no longer working:

```
$ elm  package install evancz/start-app
elm-package-unwrapped: /usr/bin/git: fileAccess: permission denied (Operation not permitted)
```

That is one strange error – what is Elm trying to do with /usr/bin/git? I have no problems accessing the git executable:

```
-rwxr-xr-x  1 root  wheel  18176  2 Jun 23:37 /usr/bin/git*
```

**Comment by thekidder** [comment] 2015-07-01 15:28
I'm also seeing this on El Capitan. This is with a fresh install of Elm 0.15.1

**Comment by thekidder** [comment] 2015-07-03 03:22
Looks like this is the same issue as https://github.com/haskell/cabal/issues/2653

I've worked around it for the moment by disabling rootless (not an ideal solution, but it works):

```sudo nvram boot-args="rootless=0" ```

**Comment by mseri** [comment] 2015-07-23 13:23
The bug is now known and fixed in ghc-7.10. Sadly it will not be back ported to 7.8: `https://ghc.haskell.org/trac/ghc/blog/weekly20150721#MacOSXElCapitansupport`

I am using a custom build made with ghc-7.10.1 (using the nightly stackage) and it seems to work. It would probably be enough to recompile the official installer with it.

I had to change `vector>=0.10 && <0.11` to `vector>=0.10 && <0.11.1` to avoid a sandboxing conflict between `elm-package` and `aeson`, and I had to add `{-# LANGUAGE FlexibleContexts #-}` to `src/Docs.hs` to satisfy the new ghc. Everything seems to work, if I understand how to run the tests and they pass I will submit a PR.

**Comment by michaelglass** [comment] 2015-08-06 22:53
just tried with latest 10.11 and seems like `sudo nvram boot-args="rootless=0"` no longer works

**Comment by michaelglass** [comment] 2015-08-06 23:02
solution: http://www.macbartender.com/system-item-setup/

**Comment by mseri** [comment] 2015-08-10 13:57
@michaelglass I don't like this solution when it's enough to move to the latest ghc and do two minor changes to the sources to solve the problem

**Comment by michaelglass** [comment] 2015-08-10 21:33
@mseri words are important, right? Should have written "work-around"

**Comment by brancusi** [comment] 2015-09-07 20:54
Hi @mseri, could you list the steps to fix this? How would I change `vector>=0.10 && <0.11` what and where is that setting? Also the other step mentioned?

Thanks

**Comment by mseri** [comment] 2015-09-07 21:05
@michaelglass, sorry I didn't mean to be rude

@brancusi: if you want to recompile elm-package, the incriminated "vector" line is in the file elm-package.cabal. However, if you clone the last version of the repository the line has been correctly edited (https://github.com/elm-lang/elm-package/blob/master/elm-package.cabal#L140). You may still need to add `{-# LANGUAGE FlexibleContexts #-}` at the top of `src/Docs.hs`. But I cannot guarantee, I've not recompiled it again since that comment.

**Comment by brancusi** [comment] 2015-09-07 21:40
Thanks @mseri. I got as far as `cabal install` but I then get: `cabal: /usr/bin/ar: permission denied`

Tried `sudo nvram boot-args="rootless=0"` as suggested on some of the fixes for: haskell/cabal#2653

Lesson to never upgrade this early :(

**Comment by jvoigtlaender** [comment] 2015-09-08 05:34
@mseri, @brancusi, note that whatever you get with `cabal get elm-package` is *not* the last stable release. The Elm tools are not anymore put on Hackage by default. In fact, the Hackage pages like https://hackage.haskell.org/package/elm-package explicitly say: **Deprecated**.

To install Elm tools from source these days, use what is written in the README at https://github.com/elm-lang/elm-platform. That build route gives you a newer version than what is on Hackage (0.15.1 vs. 0.15), and it already has necessary fixes like `FlexibleContexts` incorporated.

However, it still depends on using `cabal` (just not on stuff downloaded from Hackage). So if your operating system prevents you from running `cabal`, you will still be out of luck. :cry:

**Comment by mseri** [comment] 2015-09-08 07:38
@jvoigtlaender thanks for the update! Then @brancusi I think it's enough to use the new ghc and compile a fresh version of cabal. You should have no problem. I cannot test it at the moment but, if you still cannot get a working version, I can try to rebuild the package on a machine with El Capitain next week

**Comment by JHKennedy4** [comment] 2015-09-14 06:52
@mseri no luck with your fix :(

```
➜  elm-package-0.5  cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-package-0.5 (user goal)
next goal: optparse-applicative (dependency of elm-package-0.5)
rejecting: optparse-applicative-0.11.0.2, 0.11.0.1, 0.11.0 (conflict:
elm-package => optparse-applicative>=0.8.1 && <0.11)
rejecting: optparse-applicative-0.10.0, 0.9.1.1, 0.9.1, 0.9.0 (conflict:
base==4.8.1.0/installed-075..., optparse-applicative => base>=4 && <4.8)
trying: optparse-applicative-0.8.1
next goal: transformers (dependency of optparse-applicative-0.8.1)
rejecting: transformers-0.4.2.0/installed-21d..., 0.4.3.0, 0.4.2.0, 0.4.1.0
(conflict: optparse-applicative => transformers>=0.2 && <0.4)
trying: transformers-0.3.0.0
trying: http-client-0.4.22.1 (dependency of elm-package-0.5)
trying: exceptions-0.8.0.2 (dependency of http-client-0.4.22.1)
trying: transformers-compat-0.4.0.4 (dependency of exceptions-0.8.0.2)
trying: transformers-compat-0.4.0.4:-two
rejecting: transformers-compat-0.4.0.4:-three (conflict:
transformers==0.3.0.0, transformers-compat-0.4.0.4:three =>
transformers>=0.4.1 && <0.5)
rejecting: transformers-compat-0.4.0.4:+three (manual flag can only be changed
explicitly)
Dependency tree exhaustively searched.
```

**Comment by JHKennedy4** [comment] 2015-09-14 07:18
Success after building from source, which was extremely painless despite what the docs say. Could even be made into a bash script pretty easily if people were cool with deciding on an official location for the installation.

**Comment by mrjjwright** [comment] 2015-09-25 00:16
Damn, on El Capitan and this is not working for me, are there any manual workaround instead of building from source?

**Comment by evancz** [comment] 2015-09-25 00:55
@mrjjwright, see https://github.com/elm-lang/elm-package/issues/109#issuecomment-118221478 for the workaround.

Since El Capitan is coming out officially quite soon, I am rebuilding the mac installer to use binaries that do not have this issue. I'll ping this thread when they are available for testing. Need to beat the public release.

**Comment by evancz** [comment] 2015-09-25 02:17
Can folks in this thread try [this installer](http://install.elm-lang.org/Elm-Platform-0.15.1-el-capitan.pkg) and report here if it resolves the issue?

**Comment by kimf** [comment] 2015-09-25 14:21
@evancz that installer solved it for me

**Comment by evancz** [comment] 2015-09-25 18:56
Okay, I made the typical installer point to this, so folks, just reinstall from the website and you should be all set!

**Closed by evancz** 2015-09-25 18:56 UTC

**Comment by michaelglass** [comment] 2015-09-29 21:09
confirmed fixed for me

**Comment by fbonetti** [comment] 2015-10-10 02:12
the new installer fixed the issue for me as well. El Capitan, version 10.11

**Comment by yeongsheng-tan** [comment] 2015-10-18 14:34
Tested on my OSX El-Capitan, and confirmed working, using the updated [OSX EL-Capitan Elm package installer](http://install.elm-lang.org/Elm-Platform-0.15.1-el-capitan.pkg) while working through [embedding Elm in Phoenix tutorial](https://github.com/CultivateHQ/seat_saver/wiki/2.-Adding-Elm#embedding-elm-into-phoenix)

**Comment by simonh1000** [comment] 2015-11-04 12:22
+1
