### ISSUE TITLE
Disallow `import Foo exposing (..)` in exposed modules

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-package#229] opened 2016-07-16 05:17 UTC
Although `elm-package` disallows breaking API changes in Minor and Patch versions, it is still possible to publish a Minor version which breaks other packages. Suppose I publish this:

```elm
module MyModule exposing (..)

import Foo exposing (..)
import Bar exposing (..)

foo : String -> String
foo arg =
    doSomething arg
```

If I publish this and `Foo` exposes `doSomething`, but `Bar` does not, nothing bad happens.

If `Bar` then publishes its own `doSomething`, suddenly it has broken my module (and anyone who depends on my module) because `doSomething` has become ambiguous.

Modules which explicitly enumerate all their `exposing` imports cannot go from unambiguous to ambiguous simply because another package published a new Minor version. This suggests a solution: disallow the use of `import` with `exposing (..)` in exposed modules (and their dependencies). This is a bit inconvenient to package authors, but the increased ecosystem reliability seems worth it.

This would only affect exposed modules, so application authors could still break their own builds by upgrading to a new Minor version of a package. However, since that does not disrupt the rest of the ecosystem, that seems like a fine thing to leave up to them. They can resolve it on their own without harming others.

**Comment by evancz** [comment] 2016-08-09 23:05
Duplicate of https://github.com/elm-lang/elm-make/issues/61 ;)

**Closed by evancz** 2016-08-09 23:05 UTC
