### ISSUE TITLE
Repository name with dots in elm-package.json causes runtime exception in generated js

### ISSUE THREAD

**Issue by rundis** [elm-lang/elm-package#262] opened 2017-02-26 10:26 UTC
## Context:
Github allows dots in repository names so something like `product.dufus` is valid.
However if you specify `https://github.com/user/project.dufus.git` in the repository field of elm-package.json you will get a runtime error from the generated js.

## Steps to reproduce
```bash
mkdir project.dufus && cd project.dufus && elm-package install --yes && sed -ie s/project.git/project.dufus.git/g elm-package.json && echo import Html\\nmain=Html.text \"Hello world\" > Main.elm && elm-make Main.elm && open index.html
```

## Workarounds
Don't use dot's in repository names in elm-package.json

## Discussion
For packages it's probably not a great idea to have dots in the name, but for end-user projects I don't see why this shouldn't be supported. If the decision is not support, an error message at an earlier stage would be nice.

**Comment by jvoigtlaender** [comment] 2017-02-27 07:10
Isn't this just a duplicate of https://github.com/elm-lang/elm-make/issues/106 ?

**Comment by evancz** [comment] 2017-07-10 18:16
This is disallowed in the upcoming version of things.

https://github.com/elm-lang/elm-compiler/blob/dev/src/Elm/Package.hs#L128-L129

**Closed by evancz** 2017-07-10 18:16 UTC
