### ISSUE TITLE
elm-package permission denied.

### ISSUE THREAD

**Issue by pmwhite** [elm-lang/elm-package#139] opened 2015-09-14 02:23 UTC
C:\Users\Philip>elm-make
 Some new packages are needed. Here is the upgrade plan.

Install:
 elm-lang/core 2.1.0

Do you approve of this plan? (y/n) y
 Downloading elm-lang/core
 elm-make: elm-lang-core-5204441: MoveFileEx "elm-lang-core-5204441" "2.1.0": permission denied (Access is denied.)

Fresh install on windows 10. I tried running as administrator.
 I used the http://elm-lang.org/install windows installer.

This happens with elm-package and elm-repl too.

**Comment by mark2011** [comment] 2015-10-04 03:32
I also have this problem. Wiindows 10, very fresh system

**Comment by narrative** [comment] 2015-10-19 14:57
I am able to get elm packages downloaded after moving my project to a directory outside of my 'dropbox' folder. I assume that dropbox uploading caused the MoveFileEx to fail.

**Comment by evancz** [comment] 2015-11-17 16:58
@pmwhite, does @narrative's suggestion change anything for you?

**Comment by pmwhite** [comment] 2015-11-17 17:40
For some reason, elm seems to be working for me now.  I don't know what it was though.  It was not in the drop box folder, so that probably wasn't it.

It could be something to do with antivirus; I've had access issues because of that.

**Comment by pmwhite** [comment] 2015-11-17 17:41
Sorry, didn't mean to close.

**Comment by evancz** [comment] 2015-11-17 17:46
I cannot reproduce this, so I think this issue will stay open forever unless you can provide a more detailed account of the root cause.

So I am going to close this. If it is possible to pin down a more precise cause, we should open a new issue pinpointing it so it'll be clear what changes can be made here to fix it.

Sorry to not give "the answer" :)

**Closed by evancz** 2015-11-17 17:46 UTC
Labels: potential bug

**Comment by pmwhite** [comment] 2015-11-17 17:50
I agree.

**Comment by jinjor** [comment] 2015-11-19 23:43
I'm getting the same error, but it (strangely) succeeded in the second time.
OS: Windows 7

```
C:\Elm-Project\elm-todomvc>elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    evancz/elm-html 4.0.2
    evancz/virtual-dom 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Downloading evancz/elm-html
elm-package: evancz-elm-html-49c1299: MoveFileEx "evancz-elm-html-49c1299" "4.0.2": permission denied (�����������������
����������������������)

C:\Elm-Project\elm-todomvc>elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    evancz/elm-html 4.0.2
    evancz/virtual-dom 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Downloading evancz/elm-html
Downloading evancz/virtual-dom
Packages configured successfully!
```

**Comment by igrep** [comment] 2015-11-20 02:23
To tell the truth, I ran into the same problem yesterday precisely as @jinjor experienced.

If the error happens [here](https://github.com/elm-lang/elm-package/blob/7a614594183471530bf415b03b0f57d6f959f322/src/Install/Fetch.hs#L26)

The cause might be same with https://github.com/haskell/cabal/issues/1698.

**Comment by marsojm** [comment] 2015-11-29 12:50
I'm also experiencing this problem. I have tried Elm versions 0.15 and 0.16 on windows 10 and same problem occurs on both versions.

**Comment by evizaer** [comment] 2016-01-03 23:24
I also ran into this problem trying to run "elm package install." I've tried running it from a directory in my dropbox and a directory on a secondary drive. I've also tried running it in an administrator shell to no avail. I'm on Windows 10. 

Is there a workaround for this? It prevents me from doing elm work on my primary machine. I have to run a linux vm to get it to work.

Here's the precise output:

    Some new packages are needed. Here is the upgrade plan.
    
    Install:
      elm-lang/core 3.0.0

    Do you approve of this plan? (y/n) y
    Downloading elm-lang/core
    elm-package.exe: elm-lang-core-243a31b: MoveFileEx "elm-lang-core-243a31b" "3.0.0": permission denied (Access is denied.)

**Comment by LudwikJaniuk** [comment] 2016-03-17 22:23
Had the same problem. Transcript:

```
Some new packages are needed. Here is the upgrade plan.                                                        
                                                                                                               
  Install:                                                                                                     
    elm-lang/core 3.0.0                                                                                        
    evancz/elm-effects 2.0.1                                                                                   
    evancz/elm-html 4.0.2                                                                                      
    evancz/start-app 2.0.2                                                                                     
    evancz/virtual-dom 2.1.0                                                                                   
                                                                                                               
Do you approve of this plan? (y/n) y                                                                           
Downloading elm-lang/core
elm-make.exe: elm-lang-core-243a31b: MoveFileEx "elm-lang-core-243a31b" "3.0.0": permission denied (Access is denied.)                                                                                      
```

**Comment by jvoigtlaender** [comment] 2016-03-17 22:33
@LudwikJaniuk, this is a closed issue. If you have an erroneous case now and with current version of Elm, you should probably open a new issue, and describe your situation in exact detail.

**Comment by moneyonrails** [comment] 2016-08-08 02:58
elm-repl is getting permission denied on windows. Does anyone has an idea how to solve this issue?

**Comment by boiledice** [comment] 2016-08-20 18:36
This happens for me as well windows 10 with McAfee antivirus: 
```
---- elm-repl 0.17.1 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> "asd"
elm-make: elm-lang-virtual-dom-cdc7373: MoveFileEx "elm-lang-virtual-dom-cdc7373" "elm-lang\\virtual-dom\\1.1.0": permission denied (Access is denied.)
```


Check if disabling your antivirus realtime scan helps. This happens intermittently for me. But I was able to get it working right everytime I start it after disabling realtime virus protection on my computer. Enabling the realtime protection seems to bring the issue back for me. Seems like the antivirus assumes that this behavior matches some virus behavior and stops this action from happening.

**Comment by SamuelWr** [comment] 2017-04-23 23:19
This happened for me too when running elm commands from the VS Code extension. Adding the elm install folder to Windows Defender's exklusion list fixed it.

This was on Windows 10, and running the commands manually from the command line always worked.

**Comment by corydeppen** [comment] 2017-07-08 21:21
Is it safe to say anyone using a machine that has virus scanning enabled without a way to disable (read: corporate PC) is pretty much out of luck when it comes to using the REPL and Elm more broadly? I've tried using `elm-repl` in Git Bash as Admin on Win10 and get the same errors reported in this thread. Even `elm make` shows the same permission denied error. I'd like to at least understand what Elm needs access to in order to get a dev environment functional.

**Comment by evancz** [comment] 2017-07-10 23:28
I have a theory on why this is happening here https://github.com/elm-lang/elm-package/issues/230#issuecomment-314265370

If that's not it, we will still see this with 0.19 and can make a new issue.

**Comment by caw** [comment] 2018-04-20 00:28
I wonder if there is any workaround for this at the moment?
I  have a windows 10 machine at work with very limited ability to turn things on and off!
thanks!

**Comment by jonator** [comment] 2018-08-16 20:46
I had this problem, restarting my machine worked.
