### ISSUE TITLE
Show reason for dependency conflict

### ISSUE THREAD

**Issue by JustusAdam** [elm-lang/elm-package#119] opened 2015-08-13 18:41 UTC
## Current situation

If your projects has dependencies with internal version conflicts, like

{( p₂ | 1.0.0 ≤ v < 2.0), ( p₃ | 1.0.0 ≤ v < 2.0)} ⇒ p₁ ⋏ {( p₂ | 2.0.0 ≤ v < 3.0.0)} ⇒ p₃

The error message thrown when trying to install p₁ is just

> Error: Unable to find a set of packages that will work with your constraints.

## The problem

This requires manual dependency tracing to find the offending package(s) which, for even marginally larger projects, can be very laborious.

## Solution?

Since the package manager resolves and tests the constraints anyway why not have him spit out whatever the last and final encountered conflict was? Preferably with a resolution trace attached, sort of like cabal does it.

I imagine something like this:

```
Error: Unable to find a set of packages that will work with your constraints.

tried resolving dependencies for: p₁
tried resolving dependencies for: p₃
encountered conflict with p₂ : 
     p₁ requires version [1.0.0  2.0.0)
     p₃ requires version [2.0.0  3.0.0) 
```

Or similar.

It does not matter whether this is the actual offending package (in the sense of being the one that needs fixing) but it gives you a start of where to look for the conflicts origin.

**Comment by jessitron** [comment] 2015-09-10 16:14
+1
I hit this too, and the message didn't give me a clear picture of what to do about it.

**Comment by ilkka** [comment] 2015-09-27 14:01
I hit this too, and thought that perhaps `Solver` could use `Data.Either` instead of `Maybe`. I'm a total Haskell newbie but wanted to give it a shot anyway, so the first thing I did was come up with a `stack.yaml` that seems to work. Here it is for posterity:

```yaml
# For more information, see: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-2.22

# Local packages, usually specified by relative directory name
packages:
- location:
    git: https://github.com/elm-lang/elm-compiler.git
    commit: 7fbdee067b494c0298d07c944629aaa5d3fa82f5
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - blaze-html-0.7.1.0
  - blaze-markup-0.6.3.0
  - blaze-builder-0.3.3.4
  - mtl-2.2.1
  - transformers-0.4.3.0
  - transformers-compat-0.4.0.4

# Override default flag values for local packages and extra-deps
flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 0.1.4.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
```

**Comment by thSoft** [comment] 2015-11-20 09:03
+1 Still reproducible with elm package 0.16.0.

**Comment by jvoigtlaender** [comment] 2015-11-23 17:18
There's a pull request implementing more or less this feature now: https://github.com/elm-lang/elm-package/pull/177, courtesy of @ento. See whether you like it, and comment with possible suggestions for improvement?

**Comment by felixguendling** [comment] 2016-05-16 16:57
I wanted to get started with elm. Sadly, until now it has been a unpleasant experience:
One interesting feature of elm seems to be elm-reactor. So I wanted to try it out with https://github.com/evancz/elm-examples (as stated in the elm-reactor readme).
It looks like noone has updated it to 0.17.0. When trying to fix this, I get the error stated here: "Error: Unable to find a set of packages that will work with your constraints."
Same for https://github.com/evancz/start-app. Looks like the whole introduction material for elm is not ready for 0.17.0.
This message is not helping and a bit daunting for a newbie like me because I don't know how to fix this.
The issue has been open since a long time and there is a pull-request. Is there any hope? I think this is really important, especially for new-comers who don't have a clue how to resolve the conflict.

**Comment by ilkka** [comment] 2016-05-16 17:03
@felixguendling I think your best bet is http://guide.elm-lang.org, that seems to be up to date for Elm 0.17. Elm-examples hasn't been updated since January by the look of it so it's seriously out of date.

**Comment by felixguendling** [comment] 2016-05-17 15:56
Thanks, this introduction is great and up to date. Perhaps the other outdated repositories should be removed, replaced by a link to this intro (guide.elm-lang.org) or (preferably) be updated.

Regarding this issue: is there anything blocking the PR from being merged? I think this would be a great improvement for the package manager.

**Comment by evancz** [comment] 2016-06-01 08:14
Check out the improvements shown in https://github.com/elm-lang/elm-package/pull/177#issuecomment-222916014.

The particular suggestion given here is likely to say relatively crazy things. Search goes from latest versions to oldest versions, so the final clash is likely to be not very relevant to what you want. In other words, I agree that this is a problem, but I do not see the overall idea here working just based on the prose description.

So I will close this one. Once it is possible to use the new error messages, keep your eyes out for stuff it does poorly on. If you find something, please open a new issue with an http://sscce.org/ showing the exact `elm-package.json` and the bad message. (Ideally lets not get into discussion of possible fixes in the same issues.) It is most important to get examples and data than to think of solutions abstractly.

**Closed by evancz** 2016-06-01 08:14 UTC
Labels: enhancement, problem
