### ISSUE TITLE
Package retrieval needs to be more robust.

### ISSUE THREAD

**Issue by jonoabroad** [elm-lang/elm-package#178] opened 2015-11-24 23:21 UTC
When running `elm-package` commands I quite often get the following error:

```
Downloading elm-lang/core

Error: failed with 'InternalIOException recv: resource vanished (Connection reset by peer)' when sending request to
    <http://github.com/elm-lang/core/zipball/3.0.0/>
```

I am sure this is due to my shocking internet connectivity, but it would be nice if elm tried a few times, rather than giving failing on what appears to be the first attempt.

This is probably related to #151

**Comment by jvoigtlaender** [comment] 2015-11-25 06:12
Actually, a duplicate of this other issue: https://github.com/elm-lang/elm-package/issues/163?

**Comment by jonoabroad** [comment] 2015-11-25 06:34
:+1:

**Comment by jvoigtlaender** [comment] 2015-11-25 06:47
Okay, closing this one here, then.

**Closed by jvoigtlaender** 2015-11-25 06:47 UTC
