### ISSUE TITLE
Confusing error message for malformed elm-package json

### ISSUE THREAD

**Issue by zgotsch** [elm-lang/elm-package#142] opened 2015-09-18 17:18 UTC
Running `elm-package install` with broken json (trailing comma in dependencies) gives an unhelpful error message:
```
Error: Error reading file elm-package.json:
    Failed reading: satisfy
```
It might be nice to give an indication of where to look to fix the broken json.

Here's the broken json I was using:
```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/PROJECT.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "2.1.0 <= v < 3.0.0",
        "evancz/start-app": "2.0.0 <= v < 3.0.0",
        "evancz/elm-html": "4.0.1 <= v < 5.0.0",
    },
    "elm-version": "0.15.1 <= v < 0.16.0"
}
```

**Comment by rubytree** [comment] 2015-11-23 02:11
@evancz It is error message from JSON parser. Issue has been resolved in release 0.10.0.0 https://github.com/bos/aeson/issues/113

**Comment by maeehart** [comment] 2016-02-22 07:26
So,  aeson used in elm should be updated. Does anybody know if that is planned? I have this problem also.

**Comment by jvoigtlaender** [comment] 2016-02-25 10:23
@rubytree, @maeehart, it seems just updating the `aeson` version does not really buy much. For the malformed `elm-package.json` example above, Elm 0.16, using `aeson >= 0.7 && < 0.9`, gives the message
```
Error: Error reading file elm-package.json:
    Failed reading: satisfy
```
already quoted above.

After recompiling with `aeson >= 0.11 && < 0.12`, that error message becomes:
```
Error: Error reading file elm-package.json:
    Error in $: Failed reading: satisfy
```
So the promise that a newer `aeson` will solve the issue goes unfulfilled.

**Comment by eschr** [comment] 2016-05-12 19:36
I am getting this error when trying to install elm-lang/html

"Error: Unable to get elm-package.json for elm-lang/html 1.0.0
Failed reading: satisfy"

Is anyone else experiencing this?

**Comment by jvoigtlaender** [comment] 2016-05-12 19:42
@eschr, please post your `elm-package.json` file here.

**Comment by jvoigtlaender** [comment] 2016-05-12 19:44
Ah, scrap that, your message seems to say the problem is with `elm-lang/html`'s `elm-package.json`.

Which Elm version are you using?

**Comment by eschr** [comment] 2016-05-12 20:05
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}

**Comment by michaelperrygoodman** [comment] 2016-05-22 18:09
My elm-package.json looks almost identical (Pragmatic Studios intro tutorial) and I am having the same difficulty.

**Closed** 2016-06-01 04:02 UTC
Labels: problem

**Comment by evancz** [comment] 2016-06-01 07:23
I improved the message to be like this:

```
I cannot parse the JSON. Maybe a comma is missing? Or there is an extra one?
It could also be because of mismatched brackets or quotes.

You can also check out the following example to see what it should look like:
<https://raw.githubusercontent.com/elm-lang/html/master/elm-package.json>
```

It would be better to give a specific error and location, but it does not seem to be possible with the existing libraries. So I [asked](https://www.reddit.com/r/haskell/comments/4lxmu6/library_request_validate_json_structure_with_nice/) to see if anyone is willing to make something that'd improve aeson. Maybe something okay will happen there.

**Comment by Kennedy-s** [comment] 2017-05-03 10:15
Even me i got the same message after installing packages and am stacked now,,,anyone who can help us plzz
