### ISSUE TITLE
Be git host agnostic

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-package#235] opened 2016-08-31 16:57 UTC
I personally perfer gitlab.com over github.com, and would like to host my Elm packages there inorder to use their CI infrastructure to execute tests and such. Right now `elm-package` is opinionated about using github.com as the one and only public repo host. I feel like this is an unnecessary restriction and one that ties Elm to a specific corporation which is contrary to open source principles. So long as the `.git` endpoint is reachable, I think it should be ok to host an Elm package there.

**Comment by JoeyEremondi** [comment] 2016-08-31 16:59
Duplicate of https://github.com/elm-lang/elm-package/issues/189.

**Closed** 2016-08-31 17:00 UTC
