### ISSUE TITLE
elm-package install fails without clear explanation

### ISSUE THREAD

**Issue by z5h** [elm-lang/elm-package#148] opened 2015-10-02 19:32 UTC
In my package.json I have
```json
    "dependencies": {
        "elm-lang/core": "2.1.0 <= v < 3.0.0",
        "evancz/elm-effects": "1.0.0 <= v < 2.0.0",
        "evancz/elm-html": "4.0.1 <= v < 5.0.0",
        "evancz/start-app": "2.0.0 <= v < 3.0.0",
        "sgraf812/elm-graph": "1.1.0 <= v < 2.0.0"
    },
    "elm-version": "0.15.1 <= v < 0.16.0"

```

I do 
```
> elm-package install mgold/elm-date-format                                                                      ⏎
To install mgold/elm-date-format I would like to add the following
dependency to elm-package.json:

    "mgold/elm-date-format": "1.0.1 <= v < 2.0.0"

May I add that to elm-package.json for you? (y/n) y


Error: Unable to find a set of packages that will work with your constraints.
```

Not clear what the problem is.

**Comment by jvoigtlaender** [comment] 2015-10-02 19:37
Duplicate of #119, in a way.

**Comment by z5h** [comment] 2015-10-02 19:39
@jvoigtlaender Thanks.

**Comment by jvoigtlaender** [comment] 2015-10-02 19:41
To fix your specific problem, increase elm-effects to 2.0.0.

**Comment by jvoigtlaender** [comment] 2015-10-03 05:35
@z5h, did my suggested fix solve your problem?

Can the issue here be closed?

Background: The specific issue you had run into was [this one](https://groups.google.com/forum/#!topic/elm-discuss/MrmcITtA94I) (ultimately caused by [this improvement](https://groups.google.com/forum/#!topic/elm-discuss/iJFKZ93q1wQ)).

**Comment by z5h** [comment] 2015-10-05 13:16
Sorry, busy weekend. I'll try it out today.
How did you figure out the exact details of the incompatibility?

**Comment by jvoigtlaender** [comment] 2015-10-05 17:24
Oh, I just knew it when I saw your bounds for elm-effects and start-app. :smile: 

Because I was a party to those "breaking changes" (not really "breaking", since semantic versioning policy is followed). What's described in the mailing list messages linked to in my previous comment.

**Comment by z5h** [comment] 2015-10-05 19:34
@jvoigtlaender 

`Packages configured successfully!`

Thanks.

**Comment by jvoigtlaender** [comment] 2015-10-05 19:47
Cool. Close this issue, then?

**Closed** 2015-10-05 23:04 UTC
