### ISSUE TITLE
Can't install elm-core 1.1.0 with elm-package 0.4

### ISSUE THREAD

**Issue by vasalvit** [elm-lang/elm-package#92] opened 2015-01-29 11:40 UTC
Hi all

I built _Elm 0.14.1_ from sources on my Mac (with _OSX 10.9.5_).  I hadn't issues.  Then I tried to install elm-core and I see:

```bash
mac:src user$ elm-package install elm-lang/core 1.1.0
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 1.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core

Error: <!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'">
    <title>Page not found &middot; GitHub</title>
...
```

I removed _elm-stuff_ and _elm-package.json_, I tried to rebuild _Elm 0.14.1_, I tried to install _elm-lang/core 1.0.0_, but I still has this error.  As I remember, a month ago I used _Elm 0.14_ without problems (I also built it from sources).

**Comment by johnpmayer** [comment] 2015-01-29 12:01
Looks like you're hitting github's 404 page. Are you behind a proxy?

**Comment by vasalvit** [comment] 2015-01-29 12:11
No, I don't use proxy. I can clone repo directly with git:

```bash
mac:src user$ git config --global http.proxy
mac:src user$ git config --global https.proxy
mac:src user$ git clone https://github.com/elm-lang/core.git /tmp/core
Cloning into '/tmp/core'...
remote: Counting objects: 2221, done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 2221 (delta 42), reused 0 (delta 0)
Receiving objects: 100% (2221/2221), 459.98 KiB | 57.00 KiB/s, done.
Resolving deltas: 100% (1542/1542), done.
Checking connectivity... done.
```

**Comment by vasalvit** [comment] 2015-01-29 12:13
Sorry.  I didn't want to close this issue

**Comment by johnpmayer** [comment] 2015-02-01 21:29
I'm able to reproduce this on Ubuntu, building from source

**Comment by vasalvit** [comment] 2015-02-02 07:37
I checked Ubuntu Server 14.04 and also I can't reproduce this issue.

Also I checked several versions of _elm-package_ (from hackage) on my Mac.  I found that I have this issue in all versions except _0.2_ (I can't reproduce this issue on _0.2.1_, _0.2.2_, _0.4_).

**Comment by evancz** [comment] 2015-02-02 09:42
Interesting, looking at [the constraints on http-client for the different versions](https://hackage.haskell.org/package/elm-package), it seems that we go from `0.3.*` to `0.3 <= && < 0.5` so I bet there is a regression in that library. I bet it for other reasons as well...

**Comment by johnpmayer** [comment] 2015-02-03 15:12
Yeah we should light this up for @snoyberg

**Comment by snoyberg** [comment] 2015-02-03 15:15
I'm not sure what I'm being pinged on here. I see that there's a potential issue with http-client, but I'm not sure what it is. Can someone clarify?

**Comment by johnpmayer** [comment] 2015-02-03 15:28
Still working on a minimum repro but it has to do with following 302
redirects, in this case downloading zip files from github.

**Comment by johnpmayer** [comment] 2015-02-04 04:26
Here's the repro

``` shell
136     mkdir http-client-test
137     cd http-client-test/
138     cabal sandbox init
139     cabal update
140     cabal install http-client-0.4.7 http-client-tls
141     vi GitHubZip.hs
```

``` Haskell
{-# LANGUAGE OverloadedStrings #-}
import Network
import Network.HTTP.Client
import Network.HTTP.Client.TLS

run i =
  do
    let url = "http://github.com/elm-lang/core/zipball/1.1.0/"
    let settings = tlsManagerSettings
    withSocketsDo $ withManager settings $ \man -> do
      let req = url
               { proxy = Just $ Proxy "10.0.0.216" 3128
               , redirectCount = i
               }
      httpLbs req man >>= print
```

``` shell
142     cabal repl

Prelude> :l GitHubZip.hs
*Main> run 0 -- StatusCodeException 301 (expected)
*Main> run 1 -- TooManyRedirects 302 (expected)
*Main> run 2 -- TooManyRedirects 301 (expected)
*Main> run 3 -- StatusCodeException 404 (not expected!)
```

I believe that the redirect logic rewriting the next request based on the location header is broken.

**Comment by johnpmayer** [comment] 2015-02-04 04:42
I've opened https://github.com/snoyberg/http-client/issues/103

**Comment by johnpmayer** [comment] 2015-02-04 16:12
We can update to http-client-0.4.7.1

**Comment by evancz** [comment] 2015-02-06 17:12
Great, thank you so much! :D

So I think that'll fix things for people installing through hackage, but I think it'd be good to update the installers. I've made some other tiny fixes, so maybe I can try to push them all in the next week.

**Comment by evancz** [comment] 2015-02-06 17:13
@vasalvit, if you can confirm that things work when you get the latest version of http-client, let's close this!

**Comment by johnpmayer** [comment] 2015-02-06 18:30
Let me do the proxy stuff also on all platforms before this incremental
release

**Comment by vasalvit** [comment] 2015-02-09 07:20
I built the elm-package from sources.  I can't reproduce this issue on my Mac.  Thanks a lot :+1:

**Closed** 2015-11-17 17:14 UTC
